# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [cspire, smith101]
patreon: # Replace with a single Patreon username tor
open_collective: # Replace with a single Open Collective username opensea.io
ko_fi: # Replace with a single Ko-fi username Fred
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., slack-foundry
liberapay: # Replace with a single Liberapay username tor
issuehunt: # Replace with a single IssueHunt username wiki
otechie: # Replace with a single Otechie username aspca
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://Ashley.com', 'https://libertymutal.com']
